version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-build phase...
      - mkdir -p artifacts
      - aws s3 cp s3://$S3_BUCKET/last-successful-build.tar.gz artifacts/last-successful-build.tar.gz || echo "No previous build found in S3"

  build:
    commands:
      - echo Cloning the repository...
      - git clone https://github.com/MrinalBhoumick/AppSync-Structured.git /codebuild/repo
      - cd /codebuild/repo

      - echo Creating AppSync API if it does not exist...
      - bash scripts/create-api.sh || { echo "API creation failed"; touch rollback.flag; exit 1; }

      - echo Updating schema...
      - bash scripts/update-schema.sh || { echo "Schema update failed"; touch rollback.flag; exit 1; }

      - echo Creating or updating the data source...
      - bash scripts/create-update-data-source.sh || { echo "Data source update failed"; touch rollback.flag; exit 1; }

      - echo Updating request mapping templates...
      - bash scripts/update-request-mapping-template.sh || { echo "Request mapping update failed"; touch rollback.flag; exit 1; }

      - echo Updating response mapping templates...
      - bash scripts/update-response-mapping-template.sh || { echo "Response mapping update failed"; touch rollback.flag; exit 1; }

      - echo Updating Lambda authorizer...
      - bash scripts/update-lambda-authorizer.sh || { echo "Lambda authorizer update failed"; touch rollback.flag; exit 1; }

  post_build:
    commands:
      - echo Build phase completed. Checking for rollback flag...
      - |
        if [ -f rollback.flag ]; then
          echo "Build failed. Performing rollback..."
          if [ -f artifacts/last-successful-build.tar.gz ]; then
            echo "Found previous successful build artifact. Running rollback script..."
            bash scripts/rollback.sh
          else
            echo "No previous successful build artifact found in S3. Cannot perform rollback."
          fi
          exit 1
        else
          echo "Build succeeded. No rollback needed."
          echo Packaging the repository...
          mkdir -p artifacts
          tar --exclude='./artifacts' -czf artifacts/last-successful-build.tar.gz .
          echo Uploading package to S3...
          aws s3 cp artifacts/last-successful-build.tar.gz s3://$S3_BUCKET/last-successful-build.tar.gz
        fi

artifacts:
  files:
    - "**/*"

# Use the custom Docker image
image: 992382729083.dkr.ecr.ap-south-1.amazonaws.com/codebuild-custom-aml2023:latest
