version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y jq
      - wget https://github.com/mikefarah/yq/releases/download/v4.14.2/yq_linux_amd64 -O /usr/local/bin/yq
      - chmod +x /usr/local/bin/yq

  pre_build:
    commands:
      - echo Loading environment variables...
      - echo Printing directory structure...
      - ls -R

  build:
    commands:
      # - echo Updating schema...
      # - bash scripts/update-schema.sh

      - echo Updating Lambda authorizer...
      - bash scripts/update-lambda-authorizer.sh

      - echo Updating request mapping templates...
      - bash scripts/update-request-mapping-template.sh

      - echo Updating response mapping templates...
      - bash scripts/update-response-mapping-template.sh
