version: 0.2

phases:
  build:
    commands:
      - echo Creating AppSync API if it does not exist...
      - bash scripts/create-api.sh

      - echo Updating schema...
      - bash scripts/update-schema.sh

      - echo Creating or updating the data source...
      - bash scripts/create-update-data-source.sh

      - echo Updating request mapping templates...
      - bash scripts/update-request-mapping-template.sh

      - echo Updating response mapping templates...
      - bash scripts/update-response-mapping-template.sh

      - echo Updating Lambda authorizer...
      - bash scripts/update-lambda-authorizer.sh

artifacts:
  files:
    - SAM/update-appsync.yml
    - SAM/update-queries.yml
    - SAM/update-mutations.yml

# Use the custom Docker image
image: 992382729083.dkr.ecr.ap-south-1.amazonaws.com/codebuild-custom-aml2023:latest
