name: Status Update

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Pull Request status
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: |
            Build Status: ${{ job.status == 'success' && '✅ Build succeeded' || '❌ Build failed' }}
