name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::992382729083:role/GitHubActionsRole
          role-session-name: GitHubActionsSession
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Docker image
        run: |
          docker pull 992382729083.dkr.ecr.ap-south-1.amazonaws.com/codebuild-custom-aml2023:latest

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/codebuild/repo -e S3_BUCKET=${{ secrets.S3_BUCKET }} 992382729083.dkr.ecr.ap-south-1.amazonaws.com/codebuild-custom-aml2023:latest /bin/bash -c "
            mkdir -p artifacts && \
            ARTIFACTS=$(aws s3 ls s3://$S3_BUCKET/ --recursive | grep 'last-successful-build.tar.gz' || echo 'No previous build found in S3') && \
            if [ \"$ARTIFACTS\" != \"No previous build found in S3\" ]; then \
              echo 'Previous build artifact found. Downloading...'; \
              aws s3 cp s3://$S3_BUCKET/last-successful-build.tar.gz artifacts/last-successful-build.tar.gz; \
            fi && \
            echo Creating AppSync API if it does not exist... && \
            bash scripts/create-api.sh || { echo 'API creation failed'; touch rollback.flag; exit 1; } && \
            echo Updating schema... && \
            bash scripts/update-schema.sh || { echo 'Schema update failed'; touch rollback.flag; exit 1; } && \
            echo Creating or updating the data source... && \
            bash scripts/create-update-data-source.sh || { echo 'Data source update failed'; touch rollback.flag; exit 1; } && \
            echo Updating Mapping templates... && \
            bash scripts/update-mapping-template.sh || { echo 'Mapping update failed'; touch rollback.flag; exit 1; } && \
            echo Updating Lambda authorizer... && \
            bash scripts/update-lambda-authorizer.sh || { echo 'Lambda authorizer update failed'; touch rollback.flag; exit 1; }"

      - name: Wait for CodePipeline to complete
        run: |
          sleep 45

      - name: Get latest CodePipeline execution ID
        id: get-execution-id
        run: |
          EXECUTION_ID=$(aws codepipeline list-pipeline-executions --pipeline-name ${{ secrets.CODEPIPELINE_NAME }} --query 'pipelineExecutionSummaries[0].pipelineExecutionId' --output text)
          echo "Pipeline execution ID: $EXECUTION_ID"
          echo "::set-output name=execution-id::$EXECUTION_ID"

      - name: Check CodePipeline status
        id: codepipeline-status
        run: |
          PIPELINE_STATUS=$(aws codepipeline get-pipeline-execution --pipeline-name ${{ secrets.CODEPIPELINE_NAME }} --pipeline-execution-id ${{ steps.get-execution-id.outputs.execution-id }} --query 'pipelineExecution.status' --output text)
          echo "Pipeline status: $PIPELINE_STATUS"
          echo "::set-output name=status::$PIPELINE_STATUS"

      - name: Post Build Status on Commit
        run: |
          if [ "${{ steps.codepipeline-status.outputs.status }}" == "Succeeded" ]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.XGITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"body": "✅ Build succeeded"}' \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments"
          else
            curl -X POST \
              -H "Authorization: token ${{ secrets.XGITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"body": "❌ Build failed"}' \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments"
            exit 1
          fi
        env:
          XGITHUB_TOKEN: ${{ secrets.XGITHUB_TOKEN }}
