name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::992382729083:role/GitHubActionsRole
          role-session-name: GitHubActionsSession
          audience: sts.amazonaws.com

      - name: Build and Deploy
        uses: docker://992382729083.dkr.ecr.ap-south-1.amazonaws.com/codebuild-custom-aml2023:latest
        with:
          entrypoint: "/bin/bash"
          args: "-c 'mkdir -p artifacts && /usr/local/bin/aws s3 cp s3://$S3_BUCKET/last-successful-build.tar.gz artifacts/last-successful-build.tar.gz || echo \"No previous build found in S3\" && echo Pre-build phase... && bash -c \"if [ -f rollback.flag ]; then echo \"Build failed. Performing rollback...\"; ARTIFACTS=$(aws s3 ls s3://$S3_BUCKET/ --recursive | grep \'.tar.gz\' || echo \"No artifacts found in S3\"); if [ \"$ARTIFACTS\" != \"No artifacts found in S3\" ]; then LATEST_ARTIFACT=$(echo \"$ARTIFACTS\" | sort | tail -n 1 | awk \'{print $4}\'); echo \"Found previous successful build artifact: $LATEST_ARTIFACT. Running rollback script...\"; aws s3 cp s3://$S3_BUCKET/$LATEST_ARTIFACT artifacts/latest-build.tar.gz; chmod +x scripts/rollback.sh; bash scripts/rollback.sh || { echo \"Rollback failed\"; exit 1; }; else echo \"No previous build artifact found in S3. Cannot perform rollback.\"; exit 1; fi; else echo \"Build succeeded. No rollback needed.\"; echo Packaging the repository...; mkdir -p artifacts; tar --exclude=\'./artifacts\' -czf artifacts/last-successful-build.tar.gz .; echo Uploading package to S3...; aws s3 cp artifacts/last-successful-build.tar.gz s3://$S3_BUCKET/last-successful-build.tar.gz || { echo \"Upload to S3 failed\"; exit 1; } fi'"

      - name: Post Build Status
        run: |
          if [ -f rollback.flag ]; then
            echo "Build failed. Rolling back..."
            gh pr comment ${{ github.event.pull_request.number }} --body "$(printf '❌ Build failed. Rolled back to the previous successful build')"
          else
            echo "Build succeeded"
            gh pr comment ${{ github.event.pull_request.number }} --body "$(printf '✅ Build succeeded')"
          fi
        env:
          GH_TOKEN: ${{ secrets.XGITHUB_TOKEN }}
